
// Objective-C API for talking to the following Go packages
//
//	A1/A1
//
// File is generated by gomobile bind. Do not edit.
#ifndef __A1_FRAMEWORK_H__
#define __A1_FRAMEWORK_H__

#include "A1.objc.h"
#include "Universe.objc.h"

#endif
